name: Covid Data Update

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"
jobs:
  Data:

    runs-on: ubuntu-latest 
    steps:

    - name: 🛎️ Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # fetch all history so that last modified date-times are accurate

    - name: Setup GitHub Action for R language
      uses: r-lib/actions/setup-r@v1

    - name: Install system dependencies
      run: sudo apt-get install libudunits2-dev libcurl4-openssl-dev libgdal-dev
      
    - name: Checkout covidData
      uses: actions/checkout@v2
      with:
        repository: reichlab/covidData
        token: ${{secrets.github_token}}
        path: covidData

    - name: Install R dependencies (for covidData + covidHubUtils)
      run: Rscript scripts/install_dependencies.R
      env:
        GITHUB_PAT: ${{ secrets.github_token }}

    - name: Python Set-Up
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
    - name: Install requirements
      run: pip install -r requirements.txt
           pip install -e .

    - name: Get data truths
      run: bash scripts/update_data.sh

    - name: Push generated files to GitHub
      run: bash scripts/push.sh
      env:
        GITHUB_PAT: ${{ secrets.github_token }}
